# Generated by Django 5.2.11 on 2026-03-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_ticket_problem_solver_ticket_resolved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='problem_solver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
