# Generated by Django 5.2.11 on 2026-04-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
