# Generated by Django 5.2.11 on 2026-03-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
