# Generated by Django 5.2.11 on 2026-04-08 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_leaverequest_leave_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='id',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_rejected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='department_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='department_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='resolved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_id',
            field=models.CharField(default=2, editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
