# Generated by Django 5.2.11 on 2026-04-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_leaverequest_leave_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_days',
            field=models.FloatField(default=1),
        ),
    ]
