# Generated by Django 5.2.11 on 2026-05-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_leaverequest_leave_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('block', models.CharField(max_length=50)),
                ('flat', models.CharField(max_length=50)),
                ('tower', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('Non Tower', 'Non Tower'), ('Amenities', 'Amenities')], max_length=50)),
                ('area', models.CharField(choices=[('STP Area', 'STP Area'), ('Parking Area', 'Parking Area'), ('Temple Area', 'Temple Area'), ('Club House', 'Club House')], max_length=50)),
                ('issue', models.CharField(choices=[('Civil', 'Civil'), ('Plumbing', 'Plumbing'), ('Waterproofing', 'Waterproofing'), ('Door and Windows', 'Door and Windows'), ('Flooring', 'Flooring'), ('Maintenance Sampoorna', 'Maintenance Sampoorna')], max_length=100)),
                ('problem', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='customer_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
