# Generated by Django 5.2.11 on 2026-04-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_leaverequest_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
