# Generated by Django 5.2.11 on 2026-05-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_customerquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerquery',
            name='block',
        ),
        migrations.AddField(
            model_name='customerquery',
            name='other_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerquery',
            name='other_issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerquery',
            name='other_tower',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerquery',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
        migrations.AddField(
            model_name='customerquery',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='customerquery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customerquery',
            name='area',
            field=models.CharField(choices=[('STP Area', 'STP Area'), ('Parking Area', 'Parking Area'), ('Temple Area', 'Temple Area'), ('Club House', 'Club House'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customerquery',
            name='flat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customerquery',
            name='issue',
            field=models.CharField(choices=[('Civil Work', 'Civil Work'), ('Plumbing Work', 'Plumbing Work'), ('Waterproofing Work', 'Waterproofing Work'), ('Door and Windows', 'Door and Windows'), ('Flooring Work', 'Flooring Work'), ('Painting Work', 'Painting Work'), ('Electrical Work', 'Electrical Work'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customerquery',
            name='tower',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('Non Tower', 'Non Tower'), ('Amenities', 'Amenities'), ('Other', 'Other')], max_length=50),
        ),
    ]
