# Generated by Django 5.2.11 on 2026-05-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_customerquery_block_customerquery_other_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerquery',
            name='flat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
