# Generated by Django 5.2.11 on 2026-05-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_customerquery_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerquery',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
