# Generated by Django 5.2.11 on 2026-06-12 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_customerquery_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerquery',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=50),
        ),
        migrations.CreateModel(
            name='MaintenanceScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='jrdme.rbpl@rajat-group.com', max_length=254)),
                ('scope_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scope_form', to='dashboard.customerquery')),
            ],
        ),
    ]
