# Generated by Django 5.2.11 on 2026-06-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_customerquery_status_maintenancescope'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancescope',
            name='block',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='maintenancescope',
            name='customer_contact',
            field=models.CharField(default='NA', max_length=15),
        ),
        migrations.AddField(
            model_name='maintenancescope',
            name='customer_email',
            field=models.EmailField(default='test@test.com', max_length=254),
        ),
        migrations.AddField(
            model_name='maintenancescope',
            name='customer_name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='maintenancescope',
            name='issue_description',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='maintenancescope',
            name='issue_related',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='maintenancescope',
            name='location',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='maintenancescope',
            name='ticket_id',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
