# Generated by Django 5.2.11 on 2026-06-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_maintenancescope_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancescope',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='maintenancescope',
            name='ticket_id',
        ),
        migrations.AddField(
            model_name='maintenancescope',
            name='case_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='maintenancescope',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancescope',
            name='block',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancescope',
            name='customer_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancescope',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancescope',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancescope',
            name='issue_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancescope',
            name='issue_related',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancescope',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
