# Generated by Django 5.2.11 on 2026-06-16 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_maintenancescope_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_email', models.EmailField(max_length=254)),
                ('engineer_name', models.CharField(max_length=100)),
                ('uid', models.IntegerField()),
                ('case_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('flat_number', models.CharField(max_length=100)),
                ('issue_found_remark', models.TextField()),
                ('issue_found_area', models.TextField()),
                ('category', models.CharField(choices=[('Chargeable', 'Chargeable'), ('Non Chargeable', 'Non Chargeable')], max_length=50)),
                ('chargeable_comment', models.TextField(blank=True, null=True)),
                ('non_chargeable_comment', models.TextField(blank=True, null=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='inspection_photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='inspection_photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='inspection_photos/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='inspection_photos/')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='inspection_photos/')),
                ('material_required', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('vendor_side', models.CharField(blank=True, max_length=200, null=True)),
                ('days_required', models.IntegerField()),
                ('under_scope', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customerquery')),
            ],
        ),
    ]
