# Generated by Django 5.2.11 on 2026-06-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_siteinspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinspection',
            name='unique_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
