# Generated by Django 5.2.11 on 2026-06-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_siteinspection_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerquery',
            name='flat',
        ),
    ]
