# Generated by Django 5.2.11 on 2026-06-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_customerquery_flat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerquery',
            name='other_issue',
        ),
        migrations.RemoveField(
            model_name='customerquery',
            name='whatsapp',
        ),
        migrations.AlterField(
            model_name='customerquery',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
