# Generated by Django 5.2.11 on 2026-06-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_customerquery_other_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancescope',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
