# Generated by Django 5.2.11 on 2026-06-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_maintenancescope_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinspection',
            name='chargeable_comment',
        ),
        migrations.RemoveField(
            model_name='siteinspection',
            name='non_chargeable_comment',
        ),
        migrations.RemoveField(
            model_name='siteinspection',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='siteinspection',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='siteinspection',
            name='photo5',
        ),
    ]
