# Generated by Django 5.2.11 on 2026-06-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_siteinspection_chargeable_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinspection',
            name='vendor_side',
        ),
        migrations.AlterField(
            model_name='siteinspection',
            name='material_required',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Vendor Side', 'Vendor Side')], max_length=20),
        ),
    ]
