# Generated by Django 5.2.11 on 2026-06-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_siteinspection_vendor_side_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinspection',
            name='flat_number',
        ),
    ]
