# Generated by Django 5.2.11 on 2026-06-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_siteinspection_flat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinspection',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
