# Generated by Django 5.2.11 on 2026-06-22 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_siteinspection_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('your_name', models.CharField(max_length=100)),
                ('uid', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('case_id', models.CharField(max_length=50)),
                ('advance_amount_mentioned', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proforma_invoice', models.FileField(upload_to='proforma_invoice/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customerquery')),
            ],
        ),
    ]
