# Generated by Django 5.2.11 on 2026-06-23 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_estimateform'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('case_id', models.CharField(max_length=50)),
                ('approval_type', models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=20)),
                ('customer_remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customerquery')),
            ],
        ),
    ]
