# Generated by Django 5.2.11 on 2026-06-23 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_advancecollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.IntegerField()),
                ('customer_name', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('case_id', models.CharField(max_length=50)),
                ('material_available', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customerquery')),
            ],
        ),
    ]
