# Generated by Django 5.2.11 on 2026-06-24 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_receivematerial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryCloser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.IntegerField()),
                ('contact_number', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('case_id', models.CharField(max_length=50)),
                ('solution_provided', models.TextField()),
                ('closer_report', models.FileField(upload_to='closer_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customerquery')),
            ],
        ),
    ]
