# Generated by Django 5.2.11 on 2026-06-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_adminuser_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20, unique=True)),
                ('uid', models.IntegerField()),
                ('customer_name', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('issue', models.TextField()),
                ('engineer', models.CharField(blank=True, max_length=100, null=True)),
                ('current_stage', models.CharField(choices=[('S0', 'New Query'), ('S1', 'Maintenance Scope'), ('S2', 'Site Inspection'), ('S3', 'Estimate'), ('S4', 'Customer Approval'), ('S5', 'Advance Collection'), ('S6', 'Material Availability'), ('S7', 'Raise Indent'), ('S8', 'Issue Material'), ('S9', 'Receive Material'), ('S10', 'Work Complete'), ('S11', 'Customer Feedback'), ('S12', 'Closed')], default='S0', max_length=10)),
                ('current_status', models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Overdue', 'Overdue')], default='New', max_length=30)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal', max_length=20)),
                ('ticket_type', models.CharField(blank=True, choices=[('Chargeable', 'Chargeable'), ('Non Chargeable', 'Non Chargeable')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
