# Generated by Django 5.2.11 on 2026-06-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_masterdashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterDashboard',
        ),
    ]
