# Generated by Django 5.2.11 on 2026-07-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_delete_masterdashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancescope',
            name='created_at',
        ),
    ]
