# Generated by Django 5.2.11 on 2026-07-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_remove_maintenancescope_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinspection',
            name='material_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
