# Generated by Django 5.2.11 on 2026-07-21 05:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_siteinspection_material_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancescope',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancescope',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
