# Generated by Django 5.2.11 on 2026-08-29 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_maintenancescope_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinspection',
            old_name='material_reason',
            new_name='details_of_material_required',
        ),
    ]
