# Generated by Django 5.2.11 on 2026-09-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_rename_material_reason_siteinspection_details_of_material_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuematerial',
            old_name='remark',
            new_name='issue_material_details',
        ),
    ]
