# Generated by Django 5.2.11 on 2026-09-23 05:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_rename_remark_issuematerial_issue_material_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('activity_type', models.CharField(choices=[('Structural', 'Structural / Concrete Work'), ('Plastering', 'Plastering'), ('Waterproofing', 'Waterproofing'), ('Tiling', 'Tiling'), ('Electrical', 'Electrical'), ('Plumbing', 'Plumbing'), ('Painting', 'Painting'), ('Finishing', 'Other Finishing')], max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.adminuser')),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('client_uuid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('template_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Re-confirmation Required', 'Re-confirmation Required'), ('Re-confirmed', 'Re-confirmed & Approved')], default='Pending', max_length=30)),
                ('filled_at_device_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('audited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_audited', to='dashboard.adminuser')),
                ('filled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_filled', to='dashboard.adminuser')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_verified', to='dashboard.adminuser')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.checklisttemplate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.qcproject')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('stage', models.CharField(choices=[('General', 'General Inspection'), ('In-Process', 'In-Process Inspection'), ('Post-Install', 'After Installation Inspection')], default='General', max_length=20)),
                ('question', models.CharField(max_length=300)),
                ('requires_photo', models.BooleanField(default=True)),
                ('requires_note', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.checklisttemplate')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('NA', 'Not Applicable')], default='Pending', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='inspection_photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='inspection_photos/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_results', to='dashboard.checklistinstance')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.adminuser')),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.checklisttemplateitem')),
            ],
            options={
                'unique_together': {('instance', 'template_item')},
            },
        ),
        migrations.CreateModel(
            name='QCIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('source', models.CharField(choices=[('verification', 'Raised during L2 verification'), ('audit', 'Raised during L3 audit')], max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Correction', 'Correction In Progress'), ('Re-inspection', 'Resolved - Pending Re-check'), ('Closed', 'Closed')], default='Open', max_length=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_issues_assigned', to='dashboard.adminuser')),
                ('checklist_item_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='dashboard.checklistitemresult')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_issues_raised', to='dashboard.adminuser')),
            ],
        ),
        migrations.CreateModel(
            name='QCSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='dashboard.qcproject')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.qcsite'),
        ),
        migrations.CreateModel(
            name='QCAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('old_value', models.CharField(blank=True, max_length=100)),
                ('new_value', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.adminuser')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='dashboard_q_object__ac8140_idx')],
            },
        ),
    ]
