# Generated by Django 5.2.11 on 2026-09-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_qcproject_checklisttemplate_checklistinstance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('CRM', 'CRM'), ('Site Engineer', 'Site Engineer'), ('Store Keeper', 'Store Keeper'), ('Maintenance', 'Maintenance'), ('L1 Inspector', 'L1 Inspector'), ('L2 Verifier', 'L2 Verifier'), ('L3 PM', 'L3 PM'), ('Viewer', 'Viewer')], default='Admin', max_length=30),
        ),
    ]
