# Generated by Django 5.2.11 on 2026-09-28 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_alter_adminuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistinstance',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_assigned_checklists', to='dashboard.adminuser'),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='l3_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='l3_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='l3_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qc_l3_submissions', to='dashboard.adminuser'),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='checklistinstance',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='qc_signatures/'),
        ),
    ]
