# Generated by Django 5.2.11 on 2026-09-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_checklistinstance_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitemresult',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='inspection_photos/'),
        ),
    ]
